name: PowerShell Core Tests

on:
  [push, pull_request]

jobs:
  pester-powershell-core:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    env:
      CITRIXUSERNAME: ${{ secrets.CITRIXUSERNAME }}
      CITRIXPASSWORD: ${{ secrets.CITRIXPASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Run Pester Tests for PowerShell Core
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.3.1 -Confirm:$false -Force
          Invoke-Pester -Path .\tests\ -Output Diagnostic
        shell: pwsh
        
      - name: Sleep for 600 seconds
        run: Start-Sleep -s 600
        shell: pwsh
