name: Run Pester Tests with PowerShell Core

on:
  [push, pull_request]

jobs:
  pester-powershell-core:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    env:
      CITRIXUSERNAME: ${{ secrets.CITRIXUSERNAME }}
      CITRIXPASSWORD: ${{ secrets.CITRIXPASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Run Pester Tests
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.3.1 -Confirm:$false -Force
          Invoke-Pester -Path .\tests\ -Output Diagnostic
        shell: pwsh
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
