name: Update Help docs

on:
  [push, pull_request]

jobs:
  update-help:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update Help docs
      run: |
        '## Help' > HELP.md
        '```' >> HELP.md
        $Help = Get-Help .\Get-CTXBinary.ps1 -Full
        $Help.Name = Get-CTXBinary.ps1
        $Help >> HELP.md
        '```' >> HELP.md
      shell: pwsh
      
    - name: Commit Changes
      run: |
        git config --global user.name "bot.github.actions"
        git add ./HELP.md
        git diff --staged --quiet || git commit -m "[BOT] updated help doc"
        git push
